# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1
context:
  name: opentelemetry-instrumentation-tortoiseorm
  version: "0.58b0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/opentelemetry_instrumentation_tortoiseorm-${{ version }}.tar.gz
  sha256: 83eb0199114edb13d31c0687905a9c15782e75414135b46b9829d1744f580076

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - opentelemetry-api >=1.12,<2.dev0
    - opentelemetry-instrumentation ==${{ version }}
    - opentelemetry-semantic-conventions ==${{ version }}
    - tortoise-orm >=0.17.0
    - pydantic >=1.10.2

tests:
  - python:
      imports:
        - opentelemetry
        - opentelemetry.instrumentation.tortoiseorm
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: OpenTelemetry Instrumentation for Tortoise ORM
  homepage: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-tortoiseorm
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - conda-forge/opentelemetry-api
