# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.64b0"

package:
  name: opentelemetry-instrumentation-tortoiseorm
  version: ${{ version }}

source:
  url: 
    https://pypi.org/packages/source/o/opentelemetry-instrumentation-tortoiseorm/opentelemetry_instrumentation_tortoiseorm-${{
    version }}.tar.gz
  sha256: 9108539712c554a567171ace27572b4a6304bc76d4d70eee1f50e94bb500989c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - opentelemetry-api >=1.12,<2.dev0
    - opentelemetry-instrumentation ==${{ version }}
    - opentelemetry-semantic-conventions ==${{ version }}
    - tortoise-orm >=0.17.0
    - pydantic >=1.10.2

tests:
  - python:
      imports:
        - opentelemetry
        - opentelemetry.instrumentation.tortoiseorm
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: 
    https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-tortoiseorm
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenTelemetry Instrumentation for Tortoise ORM
  description: |
    OpenTelemetry Instrumentation for Tortoise ORM
  repository: https://github.com/open-telemetry/opentelemetry-python-contrib

extra:
  recipe-maintainers:
    - rxm7706
    - conda-forge/opentelemetry-api
